#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored and maintained by Anthony Nordquist of the SalineOS project. http://www.salineos.com/  salinelinux@gmail.com 
## Copyright Anthony Nordquist 2012

## Set arrays for yad
Title=( "--title=Image To USB" )
WindowIcon=( "--window-icon=drive-removable-media-usb" )
Icon=( "--image=drive-removable-media-usb")
DisplayName=$(echo "$1" | awk -F '/' '{print $NF}')
Iso="$1"

## Load translations

LanguageLess="$(echo "$LANG" | awk -F '.' '{print $1}')"

if [ -f /etc/thunar-image-to-usb-script/Translations/$LanguageLess ]; then
 . /etc/thunar-image-to-usb-script/Translations/$LanguageLess
else
 . /etc/thunar-image-to-usb-script/Translations/en_US
fi

progressbar () {
tail -f /usr/bin/thunar-image-to-usb-script | yad --text="$@" "${WindowIcon[@]}" "${Title[@]}" "${Icon[@]}" --progress --pulsate --auto-close --no-buttons
}

USBDrives=""

## Check to make sure that is at least one USB drive connected to the system.
## Without this code the user will be displayed something REALLY ugly
## Pay no mind to the man behind the curtain :)

if [ "$(ls /dev/disk/by-path | grep 'usb')" != "" ]; then
 USBDriveTemp=$(find /dev/disk/by-path/* -printf %f" "%l\\n | grep -v part | grep "usb" | awk '{print $2}' | sed -e 's|../../||g')
for i in $USBDriveTemp; do 
 DriveTest=$(cat /var/log/messages.log | grep "$i" | grep "removable disk" | tail -1)
 DriveTestTwo=$(grep "$i" /proc/partitions)
 
 if [ "$DriveTest" != "" ]; then
 if [ "$DriveTestTwo" != "" ]; then
  if [ "$USBDrives" = "" ]; then
   USBDrives="$i"
  else
   USBDrives="$USBDrives $i"
  fi
 fi
 fi

## Some debug help
echo "$USBDriveTemp"
echo "$DriveTest"
echo "$DriveTestTwo"
echo "$USBDrives"

done
fi

## Error out if no USB drive is found
if [ "$USBDrives" = "" ]; then
 yad --window-icon="error" --image="error" "${Title[@]}" --text="$NODRIVES\n" --width=250 --button=$"gtk-ok:1"
 exit 0 
fi

GetDrive () {

USBDriveMenu=""

for i in $USBDrives; do
## Get the label of the disk if available
 Label=$(find /dev/disk/by-label/* -printf %f" "%l\\n | grep "$i" | awk '{print $1}' | sed -e 's|\\x20| |g')

if [ "$Label" = "" ]; then
 Label=' '
else
 Label="$Label     "
fi

DriveSize=$(grep -m 1 "$i" /proc/partitions | awk '{print $3}')

## Part Drive Size is in blocks, first we need to convert the blocks to bytes
 BlockSize=$(df -P /dev/$i | grep "blocks" | awk '{print $2}' | awk -F '-' '{print $1}')
## Multiply blocks by block size to get bytes
 SizeInBytes=$(echo "scale=2; $DriveSize * $BlockSize" | bc -l)
## Divide Bytes by 1024 to get Kilobytes
 SizeInKB=$(echo "scale=2; $SizeInBytes / 1024" | bc -l)
## Divide Kilobytes by 1024 to get Megabytes
 SizeInMB=$(echo "scale=2; $SizeInKB / 1024" | bc -l)
## Divide Megabytes by 1024 to get Gigabytes
 SizeInGB=$(echo "scale=2; $SizeInMB / 1024" | bc -l)
## Round up on Gigabytes
 SizeInGB=$(echo "scale=2; $SizeInGB + 1" | bc -l)

if [ "$USBDriveMenu" = "" ]; then
 USBDriveMenu=("$i" "$Label" "$SizeInGB" "$SizeInMB")
else
 USBDriveMenu=("$i" "$Label" "$SizeInGB" "$SizeInMB" "${USBDriveMenu[@]}")
fi

done


UseDrive=$(yad --height="350" --width="600" --text-align="center" --list  "${WindowIcon[@]}" "${Title[@]}" --column="Name" --column="Associated Label(s)" --column="Size in GiB" --column="Size in MiB" --print-column=1 --button=$"gtk-quit:3" --button=$"gtk-ok:2" --text="$SELECTDRIVE\n" "${USBDriveMenu[@]}")

ret="$?"

if [ "$ret" = "3" ]; then
 exit 0
elif [ "$ret" = "252" ]; then
 exit 0 
elif [ "$UseDrive" = "" ]; then
 yad "${Title[@]}" --window-icon="error" --image="error" --width="250" --wrap --text="$NODRIVESELECTED" --button=$"gtk-ok:1"
 GetDrive
 exit 0
fi

UseDrive=$(echo "$UseDrive" | awk -F '|' '{print $1}')

Continue

}

Continue () {

yad --width=300 --wrap --window-icon="gtk-dialog-warning" --image="gtk-dialog-warning" "${Title[@]}" --text="$USBCONFIRM1 $UseDrive $USBCONFIRM2 $DisplayName. $USBCONFIRM3" --button=$"gtk-no:1" --button=$"gtk-yes:0"

if [ "$?" != "0" ]; then
 exit
fi

## Unmount all partitions on the drive
Unmount=$(mount | grep "$UseDrive" | awk '{print $1}')

for i in $Unmount; do
 umount "$i"
 umount -l "$i"
done

progressbar "$COPYING $DisplayName $TO $UseDrive.\n" &


dd if="$Iso" of=/dev/"$UseDrive"
sync
udisks --detach /dev/"$UseDrive"

TailPID=$(pgrep -f "tail -f /usr/bin/thunar-image-to-usb")

kill $TailPID

## Notify send doesn't seem to work when run as root
## So we will end with a yad dialog here
yad "${Title[@]}" "${Icon[@]}" "${WindowIcon[@]}" --width="275" --wrap --text="$DisplayName $TO USB $COMPLETED\n" --button=$"gtk-ok"

exit 0

}


GetDrive

exit
